name: Splatoon3
version: 0.0.1
api-version: 1.13
main: Main

commands:
  startgame:
    description: Starts the game
    usage: /startgame
  stopgame:
    description: Stops the game
    usage: /stopgame
  forcemap:
    description: Changes map
    usage: /splatoon <mapName>
  splatoon:
    description: OP and Dev Commands
    usage: /splatoon <command> <data>